import 'colors'
import { program } from 'commander'
import './commands/convert-catalog'
import './commands/convert-gltf'
import './commands/convert-models'
import './commands/convert-slices'
import './commands/convert-tables'
import './commands/env'
import './commands/unpack'
import './commands/viewer'
program.parse(process.argv)
